/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spotless)
}

group = "org.mantagar.web"
version = "0.0.1-SNAPSHOT"
description = "UserEvents"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.kafka)
    api(libs.org.springframework.boot.spring.boot.starter.webmvc)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    runtimeOnly(libs.org.postgresql.postgresql)

    testImplementation(libs.com.h2database.h2)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.kafka.test)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.webmvc.test)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.restclient.test)

    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

tasks.withType<Test> {
    useJUnitPlatform()
}

spotless {
    java {
        googleJavaFormat().aosp()
    }
}