# TODO implement profiles
profile=local
spring.application.name=UserEvents
spring.datasource.url=jdbc:postgresql://localhost:5432/user_events
spring.datasource.username=localUSER
spring.datasource.password=localPASSWORD
spring.jpa.hibernate.ddl-auto=update
# debug
spring.jpa.show-sql=true
