spring.datasource.url=jdbc:postgresql://localhost:5432/user_events
spring.datasource.username=localUSER
spring.datasource.password=localPASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
